
import React from 'react';
import { 
  Home, 
  Map, 
  Plane, 
  Activity, 
  TrendingUp, 
  Settings, 
  User as UserIcon,
  Bell,
  HelpCircle,
  MessageSquareText
} from 'lucide-react';
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    dashboard: "Dashboard",
    fields: "Fields",
    drone: "Drone",
    health: "Health",
    market: "Market",
    alerts: "Alerts",
    settings: "Settings",
    profile: "Profile",
    help: "Help & Support",
    assistant: "AI Assistant",
    welcome: "Welcome back,",
    activeAlerts: "Active Alerts",
    totalFields: "Total Fields",
    recentAnalysis: "Recent Analysis",
    connectDrone: "Connect Drone",
    viewReports: "View Reports",
    marketTicker: "Live Market Prices",
    weather: "Weather Forecast",
    add_field: "Add New Field",
    crop_type: "Crop Type",
    last_analysis: "Last Analysis",
    health_score: "Health Score",
    analyze: "Start Analysis",
    upload_img: "Import Photo",
    take_photo: "Take Photo",
  },
  [Language.TELUGU]: {
    dashboard: "డాష్‌బోర్డ్",
    fields: "పొలాలు",
    drone: "డ్రోన్",
    health: "ఆరోగ్యం",
    market: "మార్కెట్",
    alerts: "హెచ్చరికలు",
    settings: "సెట్టింగులు",
    profile: "ప్రొఫైల్",
    help: "సహాయం",
    assistant: "AI సహాయకుడు",
    welcome: "తిరిగి స్వాగతం,",
    activeAlerts: "క్రియాశీల హెచ్చరికలు",
    totalFields: "మొత్తం పొలాలు",
    recentAnalysis: "ఇటీవలి విశ్లేషణ",
    connectDrone: "డ్రోన్ కనెక్ట్ చేయండి",
    viewReports: "నివేదికలు చూడండి",
    marketTicker: "లైవ్ మార్కెట్ ధరలు",
    weather: "వాతావరణ సూచన",
    add_field: "కొత్త పొలాన్ని జోడించండి",
    crop_type: "పంట రకం",
    last_analysis: "చివరి విశ్లేషణ",
    health_score: "ఆరోగ్య స్కోరు",
    analyze: "విశ్లేషణ ప్రారంభించండి",
    upload_img: "ఫోటోను దిగుమతి చేయండి",
    take_photo: "ఫోటో తీయండి",
  },
  [Language.HINDI]: {
    dashboard: "डैशबोर्ड",
    fields: "खेत",
    drone: "ड्रोन",
    health: "स्वास्थ्य",
    market: "बाज़ार",
    alerts: "अलर्ट",
    settings: "सेटिंग्स",
    profile: "प्रोफ़ाइल",
    help: "सहायता",
    assistant: "AI सहायक",
    welcome: "वापस स्वागत है,",
    activeAlerts: "सक्रिय अलर्ट",
    totalFields: "कुल खेत",
    recentAnalysis: "हालिया विश्लेषण",
    connectDrone: "ड्रोन कनेक्ट करें",
    viewReports: "रिपोर्ट देखें",
    marketTicker: "लाइव बाज़ार भाव",
    weather: "मौसम का पूर्वानुमान",
    add_field: "नया खेत जोड़ें",
    crop_type: "फसल का प्रकार",
    last_analysis: "अंतिम विश्लेषण",
    health_score: "स्वास्थ्य स्कोर",
    analyze: "विश्लेषण शुरू करें",
    upload_img: "फोटो आयात करें",
    take_photo: "फोटो लें",
  }
};

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'dashboard', icon: <Home className="w-6 h-6" /> },
  { id: 'fields', label: 'fields', icon: <Map className="w-6 h-6" /> },
  { id: 'drone', label: 'drone', icon: <Plane className="w-6 h-6" /> },
  { id: 'assistant', label: 'assistant', icon: <MessageSquareText className="w-6 h-6" /> },
  { id: 'health', label: 'health', icon: <Activity className="w-6 h-6" /> },
  { id: 'market', label: 'market', icon: <TrendingUp className="w-6 h-6" /> },
];

export const SECONDARY_NAV = [
  { id: 'profile', label: 'profile', icon: <UserIcon className="w-5 h-5" /> },
  { id: 'alerts', label: 'alerts', icon: <Bell className="w-5 h-5" /> },
  { id: 'settings', label: 'settings', icon: <Settings className="w-5 h-5" /> },
  { id: 'help', label: 'help', icon: <HelpCircle className="w-5 h-5" /> },
];
